pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'nodejs:4.2.1' }
      }
      steps {
        sh 'nvm install 4.2.1'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:17-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }
  }
}
