pipeline {
  agent none
  stages {
    stage('Install Maven') {
      agent {
        docker { image 'ubuntu:20.04' } // Use Ubuntu as the base image
      }
      steps {
        script {
          sh '''
          apt-get update
          apt-get install -y maven
          mvn --version
          '''
        }
      }
    }
    stage('Check Node.js Version') {
      agent {
        docker { image 'node:16-alpine' } // Use a Node.js Docker image
      }
      steps {
        sh 'node --version' // Verify Node.js version
      }
    }
  }
}
