pipeline {
  agent none
  stages {
    stage('Install Maven') {
      agent {
        docker { image 'ubuntu:20.04' } // Use Ubuntu as the base image
      }
      steps {
        script {
          sh '''
          apt-get update
          apt-get install -y maven
          mvn --version
          '''
        }
      }
    }
    stage('Install Node.js and Check Version') {
      agent {
        docker { image 'ubuntu:20.04' } // Use Ubuntu as the base image
      }
      steps {
        script {
          sh '''
          apt-get update
          apt-get install -y curl
          curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
          apt-get install -y nodejs
          node --version
          '''
        }
      }
    }
  }
}
